### ISSUE TITLE
build/config.env not found!

### ISSUE THREAD

**Issue by ly0koS** [abobija/idfx#12]
Hi!
I'm using ubuntu20.04 on WSL2. When I want to use idfx with the offical ESP8266_RTOS hello_world, I got this error message.

According to the espressif's manual, I can use `make all` to build the project. But when I try `idfx flash COM6` or `idfx monitor COM6` it went error...

Here are some screenshots.

![image](https://user-images.githubusercontent.com/23337709/114991592-54505580-9ecc-11eb-9a71-5d2576fc130f.png)

Below is what I got after `make all`

![image](https://user-images.githubusercontent.com/23337709/114991651-6a5e1600-9ecc-11eb-9ccf-6b2f13930b39.png)

**Comment by ly0koS** [comment]
I found out the issue...Like what mentioned [here](https://github.com/espressif/ESP8266_RTOS_SDK/blob/release/v3.4/README.md), I used `make` instead of `idf.py` which lead to the problem.

Switch to use `idf.py build` fix the problem.

**Comment by abobija** [comment]
Hi @ly0koS
Thank you for feedback.

Actually that is not problem because `idfx` should be used along with `idf.py` and does not support `make`.
Glad to hear that it works for you with `idf.py`

Btw, you can use `idfx build` which is alias for `idf.py build`
Or, you can later use `idfx all COMX` for build/flash/monitor all in once.

**Comment by ly0koS** [comment]
Thanks @abobija 
I used to use idf.py all the time. But the official README.md changed and I just followed the guide so...
Now that everything is fine I think it's time to close the issue.
Thank you for the wonderful tool!
